name: Deploy threedog App

#팀작업할떄는 팀장이 한번씩 눌러서 서버 적용하는게 서버과부화 안걸리고 괜춘할듯
#on:
#  workflow_dispatch:
#    inputs:


on:
  push:
    branches:
      - master # 또는 프로젝트의 기본 브랜치명

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build . -t djfksdl/threedog:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push djfksdl/threedog:latest
        
        
  SSH:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ssh to ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /home/ec2-user/upload
            sudo docker pull djfksdl/threedog:latest
            sudo docker stop threedog || true
            sudo docker rm threedog || true
            sudo docker run -d \
              --name threedog \
              -p 9033:9033 \
              -v /home/ec2-user/upload:/app/upload \
              djfksdl/threedog:latest